fixtures:
  repositories:
    rbenv:
      repo: "git@github.com:justindowning/puppet-rbenv.git"
      ref: 2.4.0
    stdlib:
      repo: "git@github.com:puppetlabs/puppetlabs-stdlib.git"
      ref: master
    vcsrepo:
      repo: "git@github.com:puppetlabs/puppetlabs-vcsrepo.git"
      ref: 1.3.2
    sudo:
      repo: "git@github.com:saz/puppet-sudo.git"
      ref: 5.0.0
    ssh:
      repo: "git@github.com:ghoneycutt/puppet-module-ssh.git"
      ref: 3.57.0
    # dependency for ssh
    concat:
      repo: "git@github.com:puppetlabs/puppetlabs-concat.git"
      ref: 4.2.1
  symlinks:
    workstation: "#{source_dir}"
