fixtures:
  repositories:
    rbenv:
      repo: "git@github.com:justindowning/puppet-rbenv.git"
      ref: 2.1.0
    stdlib:
      repo: "git@github.com:puppetlabs/puppetlabs-stdlib.git"
      ref: master
    vcsrepo:
      repo: "git@github.com:puppetlabs/puppetlabs-vcsrepo.git"
      ref: 1.3.2
    sudo:
      repo: "git@github.com:saz/puppet-sudo.git"
      ref: 5.0.0
  symlinks:
    workstation: "#{source_dir}"
