fixtures:
  repositories:
    rbenv:
      repo: "git@github.com:justindowning/puppet-rbenv.git"
      ref: 2.5.0
    stdlib:
      repo: "git@github.com:puppetlabs/puppetlabs-stdlib.git"
      ref: 5.2.0
    vcsrepo:
      repo: "git@github.com:puppetlabs/puppetlabs-vcsrepo.git"
      ref: 1.3.2
    sudo:
      repo: "git@github.com:saz/puppet-sudo.git"
      ref: 'v6.0.0'
    ssh:
      repo: "git@github.com:ghoneycutt/puppet-module-ssh.git"
      ref: 'v3.62.0'
    # dependency for ssh
    concat:
      repo: "git@github.com:puppetlabs/puppetlabs-concat.git"
      ref: 'v6.4.0'
    apt:
      repo: "git@github.com:puppetlabs/puppetlabs-apt.git"
      ref: 6.2.1
    inifile:
      repo: "git@github.com:puppetlabs/puppetlabs-inifile.git"
      ref: 'v5.0.1'
    resolv_conf:
      repo: "git@github.com:saz/puppet-resolv_conf.git"
      ref: 'v4.2.1'
    yumrepo_core:
      repo: "git@github.com:puppetlabs/puppetlabs-yumrepo_core.git"
      ref: 1.0.7
    sshkeys_core:
      repo: "git@github.com:puppetlabs/puppetlabs-sshkeys_core.git"
      ref: 2.1.0


  symlinks:
    workstation: "#{source_dir}"
